[2024-06-24T19:25:39.370+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: ETL_Final.encrypt_and_upload manual__2024-06-24T19:25:38.196182+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
